@echo off
set TORQHOME=%~dp0
set TORQDATA=%~dp0
set TORQAPPHOME=%~dp0

set KDBLOG=%TORQDATA%logs
set KDBHTML=%TORQHOME%html
set KDBLIB=%TORQHOME%lib
set KDBCONFIG=%TORQHOME%config
set KDBCODE=%TORQHOME%code
set KDBAPPCONFIG=%TORQAPPHOME%appconfig
set KDBAPPCODE=%TORQAPPHOME%code
set KDBHDB=%TORQDATA%hdb
set KDBWDB=%TORQDATA%wdbhdb
set KDBTPLOG=%TORQDATA%tplogs

set KDBBASEPORT=6000
set KDBSTACKID="-stackid %KDBBASEPORT%"
set TORQPROCESSES=%KDBAPPCONFIG%process.csv

set LD_LIBRARY_PATH=%LD_LIBRARY_PATH%:%KDBLIB%\w32
set PATH=%PATH%;%KDBLIB%\w32

set TORQMONIT=%TORQHOME%logs\monit

set RLWRAP="rlwrap"
set QCON="qcon"
